CREATE TABLE Genero (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	descricao VARCHAR(255),
	
	CONSTRAINT PkGenero PRIMARY KEY(id),
	CONSTRAINT UcNome UNIQUE(nome)
);

CREATE TABLE Banda (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	fkGenero INT,

	CONSTRAINT PkBanda PRIMARY KEY(id),
	CONSTRAINT FkBandaGenero FOREIGN KEY(fkGenero) REFERENCES Genero(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT UcBanda UNIQUE(nome)
);

CREATE TABLE Integrante (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	cpf VARCHAR(255),
	fkBanda INT,

	CONSTRAINT PkIntegrante PRIMARY KEY(id),
	CONSTRAINT FkIntegranteBanda FOREIGN KEY(fkBanda) REFERENCES Banda(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT UcIntegrante UNIQUE(cpf)
);